-- Oracle용 문서 저장 테이블 DDL입니다. 계정·캐릭터 테이블 DDL은 아직 포함하지 않습니다.
CREATE TABLE HERO_DOC (
  COL_NAME VARCHAR2(30)  NOT NULL,
  DOC_ID   VARCHAR2(60)  NOT NULL,
  BODY     CLOB          NOT NULL,
  UPD_DT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_HERO_DOC PRIMARY KEY (COL_NAME, DOC_ID)
);
COMMENT ON TABLE HERO_DOC IS '멀티버스 닉네임판 문서 저장소 (컬렉션/문서ID/JSON)';
